import { StudySpot } from '../types';

export const GT_SPOTS: Omit<StudySpot, 'id' | 'lastUpdated'>[] = [
  {
    name: 'Price Gilbert 2nd Floor',
    building: 'Price Gilbert Library',
    floor: '2nd',
    capacity: 80,
    currentOccupancy: 0,
    isAvailable: true,
    lat: 33.7748,
    lng: -84.3963,
    description: 'Quiet individual study carrels with great natural light.',
    amenities: ['WiFi', 'Power outlets', 'Quiet zone', 'Printing'],
  },
  {
    name: 'Crosland Tower Study Lounge',
    building: 'Crosland Tower',
    floor: '3rd',
    capacity: 40,
    currentOccupancy: 0,
    isAvailable: true,
    lat: 33.7745,
    lng: -84.3961,
    description: 'Open collaborative space, good for group work.',
    amenities: ['WiFi', 'Whiteboards', 'Group tables'],
  },
  {
    name: 'Clough Commons 3rd Floor',
    building: 'Clough Undergraduate Learning Commons',
    floor: '3rd',
    capacity: 120,
    currentOccupancy: 0,
    isAvailable: true,
    lat: 33.7752,
    lng: -84.3962,
    description: 'Large open floor with both quiet and collaborative zones.',
    amenities: ['WiFi', 'Power outlets', 'Printers', 'Quiet zone', 'Collaboration rooms'],
  },
  {
    name: 'Clough Commons 1st Floor',
    building: 'Clough Undergraduate Learning Commons',
    floor: '1st',
    capacity: 60,
    currentOccupancy: 0,
    isAvailable: true,
    lat: 33.7752,
    lng: -84.3962,
    description: 'Café-style seating near Starbucks. More ambient noise.',
    amenities: ['WiFi', 'Power outlets', 'Café nearby'],
  },
  {
    name: 'Tech Square Research Building Lobby',
    building: 'Tech Square Research Building (TSRB)',
    floor: '1st',
    capacity: 30,
    currentOccupancy: 0,
    isAvailable: true,
    lat: 33.7757,
    lng: -84.3882,
    description: 'Modern open seating area, great for evening study.',
    amenities: ['WiFi', 'Power outlets', 'Standing desks'],
  },
  {
    name: 'Student Center Dining Study Area',
    building: 'Student Center',
    floor: '2nd',
    capacity: 50,
    currentOccupancy: 0,
    isAvailable: true,
    lat: 33.7742,
    lng: -84.3957,
    description: 'Quiet overflow study space above the main dining area.',
    amenities: ['WiFi', 'Power outlets', 'Vending nearby'],
  },
  {
    name: 'CoC Atrium',
    building: 'College of Computing',
    floor: '1st',
    capacity: 35,
    currentOccupancy: 0,
    isAvailable: true,
    lat: 33.7776,
    lng: -84.3963,
    description: 'Open atrium seating — busy but lively CS atmosphere.',
    amenities: ['WiFi', 'Power outlets'],
  },
  {
    name: 'Van Leer Lounge',
    building: 'Van Leer Building',
    floor: '1st',
    capacity: 25,
    currentOccupancy: 0,
    isAvailable: true,
    lat: 33.7769,
    lng: -84.3958,
    description: 'Quiet ECE building lounge, rarely crowded.',
    amenities: ['WiFi', 'Power outlets', 'Quiet zone'],
  },
];
